select * from customer;

-- 1) Total Revenue Generated by Male and Female Customer

select gender, sum(purchase_amount) as revenue from customer group by gender;

-- 2) Which customers used a discount but still pent more than average purchase amount

select customer_id, purchase_amount from customer where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- 3) Top 5 products with the highest average reviw rating

select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating" from customer group by item_purchased order by avg(review_rating) desc limit 5;

-- 4) Analyze the difference in average Purchase Amounts for Standard vs. Express Shipping.

select shipping_type, round(avg(purchase_amount),2) from customer where shipping_type in ('standard','Express')
group by shipping_type;

-- 5) Do customers with subscriptions actually spend more? Take a look at how their average spend and total revenue compare to those who aren’t subscribed.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- 6) Which five products are most often bought with a discount applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7) Group customers into New, Returning, and Loyal based on how many past purchases they’ve made, and show how many fall into each group.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- 8) Find the top three most‑purchased products within each category.
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;